#docker run -d -p 27017:27017 phauer/mongodb
#docker ps 
#docker kill <containerid>

# test from host system:
# mongo --port 27017 --host 192.168.99.100
# or test with browser http://192.168.99.100:27017/ 
# getting port: 'run docker ps'
# getting host if using boot2docker: 'docker-machine ip <machine name>' (machine name's default is "default"). However, the host and machine name also is printed at the startup of the docker deamon

# https://hub.docker.com/_/mongo/
# https://docs.docker.com/examples/mongodb/
FROM mongo:2.6.11